-- SUPABASE COMPLETE SQL SCHEMA (UPDATED)

-- 1. PROFILES TABLE
-- Stores basic user info and roles (extends Supabase Auth)
create table public.profiles (
  id uuid references auth.users not null primary key,
  email text,
  image_url text,
  first_name text,
  last_name text,
  is_clinic boolean default false, -- TRUE if user is a clinic
  active_as_clinic boolean default false, -- To toggle clinic view
  act_as_clinic boolean default false, -- To toggle clinic view
  status bool default false,
  is_admin boolean default false, -- Admin flag
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
-- 2. CLINIC INFO TABLE
-- Stores specific details for clinic users
create table public.clinic_info (
  id uuid default uuid_generate_v4() primary key,
  profile_id uuid references public.profiles(id) on delete cascade not null,
  clinic_name text not null,
  license_number text,
  nid_number text,
  docs_url text[], -- Array of document URLs
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. LOCATION TABLES (REGIONS & AREAS)
-- Location hierarchy (initially dummy data, later Google Maps)
create table public.regions (
  id bigint generated by default as identity primary key,
  name text not null,
  center_lat float,
  center_long float
);

create table public.areas (
  id bigint generated by default as identity primary key,
  region_id bigint references public.regions(id) not null,
  name text not null,
  lat float,
  long float
);

-- 4. USERS LOCATION
-- Tracks user's current location
create table public.users_location (
  user_id uuid references public.profiles(id) not null primary key,
  current_lat float,
  current_long float,
  region_id bigint references public.regions(id),
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. CATEGORIES
-- Dynamic categories for Treatments, Training, and Clinic Services
create table public.categories (
  id bigint generated by default as identity primary key,
  title text not null,
  image_url text, 
  type text not null check (type in ('treatment', 'training', 'clinic_service')),
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 6. ITEMS / SERVICES
-- Specific items under categories (e.g., "Botox" under "Anti-Wrinkle")
create table public.items (
  id bigint generated by default as identity primary key,
  category_id bigint references public.categories(id) not null,
  title text not null,
  description text,
  price numeric,
  image_url text,
  region_id bigint references public.regions(id),
  owner_id uuid references public.profiles(id), -- Added: Link to Clinic User
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 7. MARKETING ITEMS (FEATURED & EXPLORE)
-- Controls the "Featured" and "Explore More" sections
create table public.marketing_items (
  id bigint generated by default as identity primary key,
  title text not null,
  image_url text not null,
  description text,
  type text not null, -- e.g., 'course', 'clinic_ad', 'product', 'insurance', 'finance'
  
  -- Filtering Logic
  is_featured boolean default false, -- If true, shows in Featured slider
  target_audience text check (target_audience in ('user', 'clinic', 'all')), -- Who sees this?
  
  start_date timestamp with time zone,
  end_date timestamp with time zone,
  
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 8. VIDEOS SECTION
-- For the Home page video slider
create table public.app_videos (
  id bigint generated by default as identity primary key,
  title text,
  video_url text not null,
  thumbnail_url text,
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 9. APPLICATIONS / BOOKINGS
create table public.applications (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  item_id bigint references public.items(id),
  status text default 'pending', -- 'pending', 'approved', 'rejected'
  form_data jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS POLICIES (Development Mode: Public Access)
alter table profiles enable row level security;
create policy "Public profiles" on profiles for all using (true);

alter table clinic_info enable row level security;
create policy "Public clinic_info" on clinic_info for all using (true);

alter table regions enable row level security;
create policy "Public regions" on regions for all using (true);

alter table categories enable row level security;
create policy "Public categories" on categories for all using (true);

alter table items enable row level security;
create policy "Public items" on items for all using (true);

alter table marketing_items enable row level security;
create policy "Public marketing_items" on marketing_items for all using (true);

alter table app_videos enable row level security;
create policy "Public app_videos" on app_videos for all using (true);

-- --- DUMMY DATA INSERTION ---

-- 1. Regions
INSERT INTO regions (name, center_lat, center_long) VALUES 
('London', 51.5074, -0.1278), 
('Manchester', 53.4808, -2.2426), 
('Birmingham', 52.4862, -1.8904);

-- 2. Categories
INSERT INTO categories (title, type, image_url) VALUES
-- Treatments (Normal User)
('Anti Wrinkle', 'treatment', 'https://via.placeholder.com/150?text=Anti+Wrinkle'),
('Dermal Fillers', 'treatment', 'https://via.placeholder.com/150?text=Fillers'),
('Skincare', 'treatment', 'https://via.placeholder.com/150?text=Skincare'),

-- Training (Normal User)
('Botox Training', 'training', 'https://via.placeholder.com/150?text=Botox+Training'),
('Filler Masterclass', 'training', 'https://via.placeholder.com/150?text=Filler+Class'),

-- Clinic Services (Clinic User)
('Insurance', 'clinic_service', 'https://via.placeholder.com/150?text=Insurance'),
('Marketing', 'clinic_service', 'https://via.placeholder.com/150?text=Marketing'),
('Finance', 'clinic_service', 'https://via.placeholder.com/150?text=Finance'),
('Consent Forms', 'clinic_service', 'https://via.placeholder.com/150?text=Forms');

-- 3. Marketing Items (Featured/Explore)
INSERT INTO marketing_items (title, image_url, type, is_featured, target_audience) VALUES
-- Featured for EVERYONE
('Summer Sale', 'https://via.placeholder.com/300x200?text=Summer+Sale', 'product', true, 'all'),

-- Featured for USERS
('New Botox Course', 'https://via.placeholder.com/300x200?text=Botox+Course', 'course', true, 'user'),

-- Featured for CLINICS
('Clinic Insurance Deal', 'https://via.placeholder.com/300x200?text=Insurance+Deal', 'insurance', true, 'clinic'),

-- Explore More (Not Featured)
('Finance Partners', 'https://via.placeholder.com/300x200?text=Finance', 'finance', false, 'clinic');

-- 4. App Videos
INSERT INTO app_videos (title, video_url) VALUES 
('Welcome Video', 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4');


-- --- REQUIRED SETUP STEPS ---

-- 1. Run Migration (this schema).
-- 2. Seed Users via Script:
--    Run: node scripts/admin-seed-users.js
--    This creates:
--    - Admin:  a@a.com / 11112222 (is_admin=true)
--    - User:   u@u.com / 11112222
--    - Clinic: c@c.com / 11112222 (is_clinic=true, active_as_clinic=true)

-- 3. Seed Items:
--    Run: node scripts/seed-clinic-items.js
--    This assigns items to c@c.com.

-- SEED USERS (SQL) - ROBUST VERSION
-- This script inserts users into auth.users (with instance_id) and public.profiles.

-- 1. Enable Encryption
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- 2. Insert Users into auth.users
-- We explicitly set 'instance_id' to '00000000-0000-0000-0000-000000000000' which is Supabase default.
INSERT INTO auth.users (
    instance_id,
    id,
    aud,
    role,
    email,
    encrypted_password,
    email_confirmed_at,
    raw_app_meta_data,
    raw_user_meta_data,
    created_at,
    updated_at
)
VALUES
-- Admin (a@a.com)
(
    '00000000-0000-0000-0000-000000000000',
    'a0000000-0000-0000-0000-000000000001', 
    'authenticated',
    'authenticated',
    'a@a.com',
    crypt('11112222', gen_salt('bf')), 
    now(),
    '{"provider": "email", "providers": ["email"]}',
    '{}',
    now(),
    now()
),
-- User (u@u.com)
(
    '00000000-0000-0000-0000-000000000000',
    'b0000000-0000-0000-0000-000000000002', 
    'authenticated',
    'authenticated',
    'u@u.com',
    crypt('11112222', gen_salt('bf')),
    now(),
    '{"provider": "email", "providers": ["email"]}',
    '{}',
    now(),
    now()
),
-- Clinic (c@c.com)
(
    '00000000-0000-0000-0000-000000000000',
    'c0000000-0000-0000-0000-000000000003',
    'authenticated',
    'authenticated',
    'c@c.com',
    crypt('11112222', gen_salt('bf')),
    now(),
    '{"provider": "email", "providers": ["email"]}',
    '{}',
    now(),
    now()
)
ON CONFLICT (id) DO NOTHING;

-- 3. Insert Profiles (Linked to Auth IDs)
INSERT INTO public.profiles (id, email, first_name, last_name, is_clinic, active_as_clinic, is_admin)
VALUES
-- Admin
('a0000000-0000-0000-0000-000000000001', 'a@a.com', 'Admin', 'Super', false, false, true),
-- User
('b0000000-0000-0000-0000-000000000002', 'u@u.com', 'User', 'Project', false, false, false),
-- Clinic
('c0000000-0000-0000-0000-000000000003', 'c@c.com', 'Clinic', 'Owner', true, true, false)
ON CONFLICT (id) DO UPDATE 
SET 
  is_clinic = EXCLUDED.is_clinic,
  active_as_clinic = EXCLUDED.active_as_clinic,
  is_admin = EXCLUDED.is_admin;


-- 4. Insert Clinic Info (Only for Clinic User)
INSERT INTO public.clinic_info (profile_id, clinic_name, license_number, nid_number)
VALUES
('c0000000-0000-0000-0000-000000000003', 'Super Skin Clinic', 'LIC-8888', 'NID-123456')
ON CONFLICT (id) DO NOTHING;
